require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NodeIndicesController do

  # This should return the minimal set of attributes required to create a valid
  # NodeIndex. As you add validations to NodeIndex, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NodeIndicesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all node_indices as @node_indices" do
      node_index = NodeIndex.create! valid_attributes
      get :index, {}, valid_session
      assigns(:node_indices).should eq([node_index])
    end
  end

  describe "GET show" do
    it "assigns the requested node_index as @node_index" do
      node_index = NodeIndex.create! valid_attributes
      get :show, {:id => node_index.to_param}, valid_session
      assigns(:node_index).should eq(node_index)
    end
  end

  describe "GET new" do
    it "assigns a new node_index as @node_index" do
      get :new, {}, valid_session
      assigns(:node_index).should be_a_new(NodeIndex)
    end
  end

  describe "GET edit" do
    it "assigns the requested node_index as @node_index" do
      node_index = NodeIndex.create! valid_attributes
      get :edit, {:id => node_index.to_param}, valid_session
      assigns(:node_index).should eq(node_index)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NodeIndex" do
        expect {
          post :create, {:node_index => valid_attributes}, valid_session
        }.to change(NodeIndex, :count).by(1)
      end

      it "assigns a newly created node_index as @node_index" do
        post :create, {:node_index => valid_attributes}, valid_session
        assigns(:node_index).should be_a(NodeIndex)
        assigns(:node_index).should be_persisted
      end

      it "redirects to the created node_index" do
        post :create, {:node_index => valid_attributes}, valid_session
        response.should redirect_to(NodeIndex.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved node_index as @node_index" do
        # Trigger the behavior that occurs when invalid params are submitted
        NodeIndex.any_instance.stub(:save).and_return(false)
        post :create, {:node_index => {}}, valid_session
        assigns(:node_index).should be_a_new(NodeIndex)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NodeIndex.any_instance.stub(:save).and_return(false)
        post :create, {:node_index => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested node_index" do
        node_index = NodeIndex.create! valid_attributes
        # Assuming there are no other node_indices in the database, this
        # specifies that the NodeIndex created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NodeIndex.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => node_index.to_param, :node_index => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested node_index as @node_index" do
        node_index = NodeIndex.create! valid_attributes
        put :update, {:id => node_index.to_param, :node_index => valid_attributes}, valid_session
        assigns(:node_index).should eq(node_index)
      end

      it "redirects to the node_index" do
        node_index = NodeIndex.create! valid_attributes
        put :update, {:id => node_index.to_param, :node_index => valid_attributes}, valid_session
        response.should redirect_to(node_index)
      end
    end

    describe "with invalid params" do
      it "assigns the node_index as @node_index" do
        node_index = NodeIndex.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NodeIndex.any_instance.stub(:save).and_return(false)
        put :update, {:id => node_index.to_param, :node_index => {}}, valid_session
        assigns(:node_index).should eq(node_index)
      end

      it "re-renders the 'edit' template" do
        node_index = NodeIndex.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NodeIndex.any_instance.stub(:save).and_return(false)
        put :update, {:id => node_index.to_param, :node_index => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested node_index" do
      node_index = NodeIndex.create! valid_attributes
      expect {
        delete :destroy, {:id => node_index.to_param}, valid_session
      }.to change(NodeIndex, :count).by(-1)
    end

    it "redirects to the node_indices list" do
      node_index = NodeIndex.create! valid_attributes
      delete :destroy, {:id => node_index.to_param}, valid_session
      response.should redirect_to(node_indices_url)
    end
  end

end
